Database setup
Teencodeprojects/Meal_Booking_App pull request #5
Opened 2019-12-19 21:39 UTC by Mr-emeka

I've set up the database environment for Production and Development.

2019-12-19 22:31 UTC, Mr-emeka commented
@Mohamilr dev database is the one on my machine while the Production database is the one on Heroku.

2019-12-19 22:33 UTC, Mr-emeka commented
@Rexben001 I'm having an error on Travis something to do with my database though it's passing.

2019-12-20 07:42 UTC, Rexben001 commented
> @Rexben001 I'm having an error on Travis something to do with my database though it's passing.

You need to create a db for your test on Travis

2019-12-20 08:25 UTC, Mr-emeka commented
How do I go about it @Rexben001 I'm pretty much clueless

2019-12-20 12:12 UTC, Rexben001 requested changes

2019-12-20 12:12 UTC, Rexben001 commented on src/models/db.js
I can't your test db, you only have for dev and production

2019-12-20 12:12 UTC, Rexben001 commented on .env.example
> +DB_USER = ruazooloskcdhy
This credential is public, it should be private

2019-12-23 09:24 UTC, Rexben001 commented on package.json
>      "@babel/polyfill": "^7.6.0",
How do you manage to change the env to dev or test?
You can install `cross_env`
Your test script can look like `cross-env NODE_ENV=test nyc mocha...`

2019-12-23 13:03 UTC, Rexben001 approved these changes

2019-12-23 13:03 UTC, merged